<?php

// autoload_classmap.php @generated by TYPO3

$typo3InstallDir = \TYPO3\CMS\Core\Core\Environment::getPublicPath() . '/';

return array(
    'ArminVieweg\\Dce\\' => array($typo3InstallDir . 'typo3conf/ext/dce/Classes'),
    'DRC\\AlbumGallery\\' => array($typo3InstallDir . 'typo3conf/ext/album_gallery/Classes'),
    'GridElementsTeam\\Gridelements\\' => array($typo3InstallDir . 'typo3conf/ext/gridelements/Classes'),
);
